# Generated by Django 3.0.3 on 2020-09-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0022_auto_20200925_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetails',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='stockdetails',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='stockdetails',
            name='volume',
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='dividend_yield',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='book_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='dividend',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='eps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='face_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='industry_pe',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='market_cap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='pe',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='price_to_book',
            field=models.FloatField(null=True),
        ),
    ]
