# Generated by Django 3.1 on 2020-08-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0003_auto_20200817_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='busybeaver.Ticker'),
        ),
    ]
