# Generated by Django 3.1 on 2020-09-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0014_auto_20200913_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.IntegerField(choices=[(2, 'Very Bullish'), (1, 'Bullish'), (0, 'Neutral'), (-1, 'Bearish'), (-2, 'Very Bearish')], default=0),
            preserve_default=False,
        ),
    ]
