# Generated by Django 3.1 on 2020-09-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0016_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
