# Generated by Django 3.1 on 2020-09-24 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0017_learn_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='current_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='fiftytwo_weeek_low',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='fiftytwo_week_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='today_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='today_low',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.IntegerField(blank=True)),
                ('close_price', models.IntegerField(blank=True)),
                ('pe', models.FloatField(blank=True)),
                ('market_cap', models.IntegerField(blank=True)),
                ('price_to_book', models.FloatField(blank=True)),
                ('eps', models.FloatField(blank=True)),
                ('face_value', models.IntegerField(blank=True)),
                ('dividend', models.FloatField(blank=True)),
                ('book_value', models.IntegerField(blank=True)),
                ('industry_pe', models.FloatField(blank=True)),
                ('volume', models.IntegerField(blank=True)),
                ('ticker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busybeaver.ticker')),
            ],
        ),
    ]
