# Generated by Django 3.1 on 2020-09-24 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('busybeaver', '0018_auto_20200924_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='video_url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busybeaver.ticker')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(blank=True)),
                ('purchase_price', models.FloatField(blank=True)),
                ('ticker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busybeaver.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=80)),
                ('news_source', models.CharField(max_length=50)),
                ('news_url', models.URLField(max_length=250)),
                ('company_name', models.ManyToManyField(to='busybeaver.Company')),
                ('tags', models.ManyToManyField(to='busybeaver.Ticker')),
            ],
        ),
    ]
