# Generated by Django 3.1 on 2020-09-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0019_auto_20200924_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='username',
            new_name='user',
        ),
    ]
