# Generated by Django 3.0.3 on 2020-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0021_portfolio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='purchase_price',
            field=models.IntegerField(blank=True),
        ),
    ]
