# Generated by Django 3.1 on 2020-10-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0025_auto_20200926_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='busybeaver.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learn',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='busybeaver/static/profile-pictures'),
        ),
    ]
