# Generated by Django 3.1 on 2021-02-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0030_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.IntegerField(choices=[(0, 'Like')]),
        ),
    ]
