# Generated by Django 3.1 on 2021-02-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0031_auto_20210204_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='purchase_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
