# Generated by Django 3.1.4 on 2021-03-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0037_auto_20210311_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
