# Generated by Django 3.1.4 on 2021-03-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0038_message_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='busybeaver.Ticker'),
        ),
    ]
