# Generated by Django 3.1.4 on 2021-03-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybeaver', '0039_auto_20210314_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='fiftytwo_weeek_low',
        ),
        migrations.RemoveField(
            model_name='price',
            name='fiftytwo_week_high',
        ),
        migrations.RemoveField(
            model_name='price',
            name='today_high',
        ),
        migrations.RemoveField(
            model_name='price',
            name='today_low',
        ),
        migrations.AlterField(
            model_name='price',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
